<?php
namespace myfirst;

/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface MyFirstServiceIf
{
    /**
     * @param string $filename
     */
    public function log($filename);
    /**
     * @param int $number1
     * @param int $number2
     * @return int
     */
    public function multiply($number1, $number2);
    /**
     * @param string $filename
     * @return int
     * @throws \myfirst\MyError
     */
    public function get_log_size($filename);
}
