<?php
/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ArithmeticException extends TException
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'msg',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'x',
            'isRequired' => false,
            'type' => TType::DOUBLE,
        ),
    );

    /**
     * @var string
     */
    public $msg = null;
    /**
     * @var double
     */
    public $x = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['msg'])) {
                $this->msg = $vals['msg'];
            }
            if (isset($vals['x'])) {
                $this->x = $vals['x'];
            }
        }
    }

    public function getName()
    {
        return 'ArithmeticException';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->msg);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::DOUBLE) {
                        $xfer += $input->readDouble($this->x);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ArithmeticException');
        if ($this->msg !== null) {
            $xfer += $output->writeFieldBegin('msg', TType::STRING, 1);
            $xfer += $output->writeString($this->msg);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->x !== null) {
            $xfer += $output->writeFieldBegin('x', TType::DOUBLE, 2);
            $xfer += $output->writeDouble($this->x);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
