<?php
/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Calculator_mult_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'A',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Matrix',
        ),
        2 => array(
            'var' => 'B',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Matrix',
        ),
    );

    /**
     * @var \Matrix
     */
    public $A = null;
    /**
     * @var \Matrix
     */
    public $B = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['A'])) {
                $this->A = $vals['A'];
            }
            if (isset($vals['B'])) {
                $this->B = $vals['B'];
            }
        }
    }

    public function getName()
    {
        return 'Calculator_mult_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->A = new \Matrix();
                        $xfer += $this->A->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRUCT) {
                        $this->B = new \Matrix();
                        $xfer += $this->B->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('Calculator_mult_args');
        if ($this->A !== null) {
            if (!is_object($this->A)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('A', TType::STRUCT, 1);
            $xfer += $this->A->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->B !== null) {
            if (!is_object($this->B)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('B', TType::STRUCT, 2);
            $xfer += $this->B->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
