<?php
namespace mythrift\demo;

/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface myThriftIf
{
    /**
     * @param int $callTime
     * @param string $name
     * @param array $paramMap
     * @return string[]
     */
    public function CallBack($callTime, $name, array $paramMap);
    /**
     * @param \mythrift\demo\Article $newArticle
     */
    public function put(\mythrift\demo\Article $newArticle);
}
