<?php
/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class BinaryOperation
{
    const ADDITION = 1;

    const SUBTRACTION = 2;

    const MULTIPLICATION = 3;

    const DIVISION = 4;

    const MODULUS = 5;

    static public $__names = array(
        1 => 'ADDITION',
        2 => 'SUBTRACTION',
        3 => 'MULTIPLICATION',
        4 => 'DIVISION',
        5 => 'MODULUS',
    );
}

