<?php
/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface CalculatorIf
{
    /**
     * @param \ArithmeticOperation $op
     * @return double
     * @throws \ArithmeticException
     */
    public function calc(\ArithmeticOperation $op);
    /**
     * @param \Matrix $A
     * @param \Matrix $B
     * @return \Matrix
     * @throws \MatrixException
     */
    public function mult(\Matrix $A, \Matrix $B);
    /**
     * @param \Matrix $A
     * @return \Matrix
     * @throws \MatrixException
     */
    public function transpose(\Matrix $A);
}
