/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tutrial_CONSTANTS_H
#define tutrial_CONSTANTS_H

#include "tutrial_types.h"

namespace tutorial {

class tutrialConstants {
 public:
  tutrialConstants();

  int32_t INT32CONSTANT;
  std::map<std::string, std::string>  MAPCONSTANT;
};

extern const tutrialConstants g_tutrial_constants;

} // namespace

#endif
