/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tutrial_constants.h"

namespace tutorial {

const tutrialConstants g_tutrial_constants;

tutrialConstants::tutrialConstants() {
  INT32CONSTANT = 9853;

  MAPCONSTANT.insert(std::make_pair("goodnight", "moon"));
  MAPCONSTANT.insert(std::make_pair("hello", "world"));

}

} // namespace

